name: CI Full Run
on:
  pull_request:
    branches:
      - main
      - grok/*/*
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          exec 2>&1; set -e -o pipefail
          cd tests
          for f in *.sh; do echo "## Running $f"; ./$f; echo; done
